### ISSUE TITLE
Allow different characteristics for skills

### ISSUE THREAD

**Issue by saif-ellafi** [moo-man/DarkHeresy2E-FoundryVTT#17]
Something wrong with the sheet, is that Skills are automatically linked to the "Default" characteristic.

However, in this system, skills may use different characteristics. Themselves, the skills are just a bonus between -20 and +30 to Some characteristic.

Right now it is defaulting, so for example Acrobatics is always against **Agility**. However, Acrobatics could be sometimes against **Strength**. This is not possible in the current sheet.

There are many possible solutions, I think the easiest one would be to set a dropdown in the roll window, with the **Characteristic** to be used, just before the roll. Although this would conflict with the **target** field.

**Comment by aSemy** [comment]
Adding a 'Characteristic' dropdown would be best, ideally with the 'Alternate Characteristics' (Table 3-3 pg99) being given highlighted. 

The target field should be made to update with a new number when another Characteristic from the dropdown is selected. It should still be user editable, but the number will be wiped if a new Characteristic is selected. 

Additionally the result shown in the chat screen should display the selected Characteristic.

**Comment by saif-ellafi** [comment]
Awesome, I like the proposal. Please let know if anyone would take over this feature, so we don't take it twice.
I -may- have time next week but I'll probably be incredibly slow.
