### ISSUE TITLE
[Bug] Tech Use is hidden behind Common Lore

### ISSUE THREAD

**Issue by Akeboshiwind** [moo-man/DarkHeresy2E-FoundryVTT#46]
On the `Stats` page in the `Skills` section the `Tech Use` skill is hidden behind the `Common Lore` section:

<img width="674" alt="Screenshot 2021-03-17 at 21 40 51" src="https://user-images.githubusercontent.com/8889986/111542309-7342b700-8769-11eb-97ce-48e24c624718.png">

You can see in the image above the calculated bonus and the advancement level are almost visible.

Below is an image where I've hidden the `Common Lore` section:

<img width="674" alt="Screenshot 2021-03-17 at 21 42 56" src="https://user-images.githubusercontent.com/8889986/111542505-bd2b9d00-8769-11eb-8b2d-328a4ba9476c.png">

**Comment by Vendare** [comment]
Has been resolved can be close @moo-man

**Comment by thecodex101** [comment]
Um I still have this issue on latest verison of DH and 0.8.9 
![image](https://user-images.githubusercontent.com/76156338/147272315-7336241f-30cb-4a67-8133-05ac2ee7ca7f.png)

**Comment by Akeboshiwind** [comment]
Yeah, I still have the same issue:

<img width="687" alt="Screenshot 2021-12-27 at 19 56 02" src="https://user-images.githubusercontent.com/8889986/147503248-2dcdb206-3895-4a65-b301-7b124e2c7d9e.png">
