### ISSUE TITLE
Weapon damage type is always Impact

### ISSUE THREAD

**Issue by ihraukki** [moo-man/DarkHeresy2E-FoundryVTT#48]
Sword, lasgun, plasma pistol - they all show after throwing dice weapon damage type as I (impact), thus weapon.damageType is incorrect or not fetched properly. 
![weaponproperties](https://user-images.githubusercontent.com/5791643/113099174-3a432180-9202-11eb-9a67-3154a1975b02.png)

![damage](https://user-images.githubusercontent.com/5791643/113099123-23043400-9202-11eb-95c2-a28d903f34b5.png)

**Comment by moo-man** [comment]
Fixed in #47 which will be released soon
