### ISSUE TITLE
Compendiums?

### ISSUE THREAD

**Issue by LordKnightCecilo** [moo-man/DarkHeresy2E-FoundryVTT#60]
Hey, new to this all, but, I am creating a list of Compendiums for my own game and filling them in with well, everything from DH2e, from weapons, items, talents, etc. I don't know if you'd be interested in taking and using it, but if you are, I'd be happy to share them when I'm done.

**Comment by moo-man** [comment]
Unfortunately that isn't something I can distribute, appreciate it though.
